#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
if (! file_exists(__DIR__.'/vendor/autoload.php')) {
    fwrite(
        STDERR,
        PHP_EOL.'Composer dependencies are missing.'.PHP_EOL.
        'Run:  composer install'.PHP_EOL.PHP_EOL
    );

    exit(1);
}

require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
